# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "Say hello to somebody"
    wish = f'Hello, {to}!'
    return wish

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to: str) -> None:
        self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)